OPTIMIZATION_SETTINGS = {
    'VISUALIZE_PROCESS': False,
    'VALIDATE': True,
    'INITIAL_TEMPERATURE': 250,
    'COOLING_RATE': 0.99,
    'MIN_TEMPERATURE': 0.1,
    'ITERATIONS_PER_TEMPERATURE': 100,
}


def validate_settings():
    if OPTIMIZATION_SETTINGS['VISUALIZE_PROCESS'] and OPTIMIZATION_SETTINGS['VALIDATE']:
        raise ValueError("Cannot have both VISUALIZE_PROCESS and VALIDATE set to True")
