OPTIMIZATION_SETTINGS = {
    'VISUALIZE_PROCESS': False,
    'INITIAL_TEMPERATURE': 250.0,
    'COOLING_RATE': 0.99,
    'MIN_TEMPERATURE': 0.075,
    'ITERATIONS_PER_TEMPERATURE': 50
}

VISUALIZATION_UPDATE_INTERVAL = 0.5  # seconds